version: '3.8'
services:
  backend:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on: 
      - database

  database:
    container_name: postgres
    hostname: postgres
    image: 'postgres:latest'
    ports: 
      - '5432:5432'
    restart: always
    env_file: .env
    volumes: 
      - fastify_volume:/var/lib/postgres/data
  
volumes:
  fastify_volume: {}



  